/**
 * Safe card content configuration.
 * Add new cards here only — visual styling is derived procedurally
 * by CardStyleController based on the card id.
 */

export interface SafeCardConfig {
  id: string;
  title: string;
  subtitle: string;
}

export const SAFE_CARDS_CONFIG: readonly SafeCardConfig[] = [
  { id: 'strawberry_dancing',    title: 'Strawberry Dancing',              subtitle: 'This strawberry has better moves than you.' },
  { id: 'butterfly_flying',      title: 'Butterfly Flying',                subtitle: 'Majestic. Inspirational. Useless.' },
  { id: 'taxi_7788',             title: 'Taxi 7788 Ad',                    subtitle: 'Call now. We probably answer.' },
  { id: 'fruit_circle',          title: 'Fruit Circle Dance',              subtitle: "Nature's nightclub." },
  { id: 'cat_reviews_water',     title: 'Cat Reviews Water',               subtitle: 'Still wet. 10/10.' },
  { id: 'grandma_filters',       title: 'Grandma Discovers Filters',       subtitle: 'She is now 19 again.' },
  { id: 'dog_sunglasses',        title: 'Dog With Sunglasses',             subtitle: 'Too cool to fetch.' },
  { id: 'frog_dj',               title: 'Frog DJ Set',                     subtitle: 'Ribbit remix.' },
  { id: 'man_explains',          title: 'Man Explains Nothing',            subtitle: 'Wait for it…' },
  { id: 'slime_cut',             title: 'Satisfying Slime Cut',            subtitle: 'Oddly addictive.' },
  { id: 'weather_forecast',      title: 'Dramatic Weather Forecast',       subtitle: "It's windy." },
  { id: 'motivational_potato',   title: 'Motivational Potato',             subtitle: 'You are starch-strong.' },
  { id: 'invisible_prank',       title: 'Invisible Prank',                 subtitle: 'Did you see it?' },
  { id: 'support_duck',          title: 'Emotional Support Duck',          subtitle: 'Quack therapy.' },
  { id: 'perfect_pancake',       title: 'Suspiciously Perfect Pancake',    subtitle: 'Too round.' },
  { id: 'diy_glue',              title: 'DIY With Glue',                   subtitle: 'This will not hold.' },
  { id: 'ai_celebrity',          title: 'AI Generated Celebrity',          subtitle: 'Almost believable.' },
  { id: 'overacting_actor',      title: 'Overacting Actor',                subtitle: 'Oscar-worthy in his mind.' },
  { id: 'man_runs',              title: 'Man Runs From Nothing',           subtitle: 'Cardio panic.' },
  { id: 'cat_yoga',              title: 'Cat Interrupts Yoga',             subtitle: 'Balance lost.' },
  { id: 'tech_bro',              title: 'Tech Bro Advice',                 subtitle: 'Just pivot.' },
  { id: 'barista',               title: 'Hyperactive Barista',             subtitle: 'Extra foam.' },
  { id: 'fruit_sunglasses',      title: 'Fruit With Sunglasses',           subtitle: 'Vitamin drip.' },
  { id: 'fake_lifehack',         title: 'Fake Lifehack',                   subtitle: "Doesn't work." },
  { id: 'slow_motion_jump',      title: 'Slow Motion Jump',                subtitle: 'Gravity wins.' },
  { id: 'makeup_reveal',         title: 'Dramatic Makeup Reveal',          subtitle: 'Same person.' },
  { id: 'sad_hamster',           title: 'Sad Hamster',                     subtitle: 'Existential.' },
  { id: 'dancing_broccoli',      title: 'Dancing Broccoli',                subtitle: 'Green energy.' },
  { id: 'fish_music',            title: 'Fish Reacts To Music',            subtitle: 'Vibing.' },
  { id: 'crypto_guy',            title: 'Guy Explains Crypto',             subtitle: 'Nobody understands.' },
  { id: 'edited_sunset',         title: 'Overedited Sunset',               subtitle: 'Too orange.' },
  { id: 'clumsy_ninja',          title: 'Clumsy Ninja',                    subtitle: 'Almost.' },
  { id: 'grocery_list',          title: 'Dramatic Reading Of Grocery List', subtitle: 'Milk!' },
  { id: 'cat_knocks',            title: 'Cat Knocks Glass',                subtitle: 'Classic.' },
  { id: 'fake_interview',        title: 'Fake Street Interview',           subtitle: 'Scripted.' },
  { id: 'whisper_challenge',     title: 'Whisper Challenge',               subtitle: 'What?' },
  { id: 'microwave_cooking',     title: 'Microwave Cooking',               subtitle: 'Risky.' },
  { id: 'influencer_apology',    title: 'Influencer Apology',              subtitle: 'Notes app.' },
  { id: 'dog_hat',               title: 'Dog In Tiny Hat',                 subtitle: 'Fashion icon.' },
  { id: 'slow_clap',             title: 'Slow Clap Compilation',           subtitle: 'Unnecessary.' },
  { id: 'intense_workout',       title: 'Overly Intense Workout',          subtitle: 'For what?' },
  { id: 'frog_mic',              title: 'Frog With Microphone',            subtitle: 'Podcast.' },
  { id: 'cat_judges',            title: 'Cat Judges You',                  subtitle: 'Disappointed.' },
  { id: 'fake_magic',            title: 'Fake Magic Trick',                subtitle: 'Camera cut.' },
  { id: 'emotional_bread',       title: 'Emotional Bread',                 subtitle: 'Crumb feelings.' },
  { id: 'man_dances',            title: 'Man Dances Alone',                subtitle: 'Confidence.' },
  { id: 'gym_quote',             title: 'Motivational Gym Quote',          subtitle: 'No pain.' },
  { id: 'baby_laugh',            title: 'Baby Laugh Loop',                 subtitle: 'Infinite.' },
  { id: 'robot_fail',            title: 'Robot Fails Task',                subtitle: 'Try again.' },
  { id: 'coffee_pour',           title: 'Smooth Coffee Pour',              subtitle: 'Aesthetic.' },
  { id: 'plot_twist',            title: 'Unexpected Plot Twist',           subtitle: 'Still safe.' },
  { id: 'fake_news',             title: 'Fake Celebrity News',             subtitle: 'Not true.' },
  { id: 'door_open',             title: 'Dramatic Door Open',              subtitle: 'Nothing.' },
  { id: 'cat_attitude',          title: 'Cat With Attitude',               subtitle: 'Royal.' },
  { id: 'bubble_wrap',           title: 'Bubble Wrap ASMR',                subtitle: 'Pop.' },
  { id: 'tourist',               title: 'Overenthusiastic Tourist',        subtitle: 'WOW.' },
  { id: 'skateboard_fail',       title: 'Skateboard Fail',                 subtitle: 'Almost.' },
  { id: 'makeup_wrong',          title: 'Makeup Tutorial Gone Wrong',      subtitle: 'Oops.' },
  { id: 'parrot',                title: 'Pet Parrot Commentary',           subtitle: 'Rude.' },
  { id: 'banana_phone',          title: 'Banana Phone',                    subtitle: 'Ring ring.' },
  { id: 'confused_math',         title: 'Confused Math Teacher',           subtitle: 'Why?' },
  { id: 'office_dance',          title: 'Dancing Office Worker',           subtitle: 'Productivity.' },
  { id: 'suspicious_sandwich',   title: 'Suspicious Sandwich',             subtitle: 'Risky bite.' },
  { id: 'rain_scene',            title: 'Dramatic Rain Scene',             subtitle: 'So deep.' },
  { id: 'horror_cat',            title: 'Fake Horror Build-up',            subtitle: 'Just a cat.' },
  { id: 'puppy_nap',             title: 'Cute Puppy Nap',                  subtitle: 'Peace.' },
  { id: 'glitch_selfie',         title: 'Glitch Filter Selfie',            subtitle: 'Distorted.' },
  { id: 'dramatic_sip',          title: 'Dramatic Sip',                    subtitle: 'Tea spilled.' },
  { id: 'life_coach',            title: 'Life Coach Yells',                subtitle: 'Manifest!' },
  { id: 'motivational_rock',     title: 'Motivational Rock',               subtitle: 'Solid advice.' },
  { id: 'cat_cucumber',          title: 'Cat Vs Cucumber',                 subtitle: 'Classic chaos.' },
  { id: 'desk_setup',            title: 'Minimalist Desk Setup',           subtitle: 'Expensive.' },
  { id: 'eyebrow_raise',         title: 'Dramatic Eyebrow Raise',          subtitle: 'Scandal.' },
  { id: 'viral_challenge',       title: 'Fake Viral Challenge',            subtitle: 'Nobody asked.' },
  { id: 'slow_blink',            title: 'Slow Blink Compilation',          subtitle: 'Trust.' },
  { id: 'shiny_sneakers',        title: 'Shiny Sneakers',                  subtitle: 'Too clean.' },
  { id: 'ice_drop',              title: 'Dramatic Ice Drop',               subtitle: 'Splash.' },
  { id: 'turtle_race',           title: 'Pet Turtle Race',                 subtitle: 'Slow but steady.' },
  { id: 'deep_quote',            title: 'Overly Deep Quote',               subtitle: 'Meaningless.' },
  { id: 'coffee_fail',           title: 'Coffee Art Fail',                 subtitle: 'Blob.' },
  { id: 'fan_whisper',           title: 'Whispering Into Fan',             subtitle: 'Vibrato.' },
  { id: 'edited_sky',            title: 'Overedited Sky',                  subtitle: 'Unreal.' },
  { id: 'banana_slip',           title: 'Banana Slip',                     subtitle: 'Cartoon physics.' },
  { id: 'serious_cat',           title: 'Serious Cat',                     subtitle: 'CEO.' },
  { id: 'motivational_alarm',    title: 'Motivational Alarm',              subtitle: 'Wake up.' },
  { id: 'dog_mirror',            title: 'Dog Confused By Mirror',          subtitle: 'Identity crisis.' },
  { id: 'frog_meditation',       title: 'Frog Meditation',                 subtitle: 'Zen.' },
  { id: 'man_plant',             title: 'Man Talks To Plant',              subtitle: 'Therapy.' },
  { id: 'fitness_hack',          title: 'Fake Fitness Hack',               subtitle: 'Nope.' },
  { id: 'dramatic_typing',       title: 'Dramatic Typing',                 subtitle: 'Email.' },
  { id: 'squirrel_snack',        title: 'Squirrel With Snack',             subtitle: 'Focused.' },
  { id: 'overhyped_trailer',     title: 'Overhyped Trailer',               subtitle: 'For nothing.' },
  { id: 'traffic_cone',          title: 'Dancing Traffic Cone',            subtitle: 'Why?' },
  { id: 'fake_psychic',          title: 'Fake Psychic Reading',            subtitle: 'Vague.' },
  { id: 'sad_violin',            title: 'Sad Violin Moment',               subtitle: 'Tiny tragedy.' },
  { id: 'glitter_explosion',     title: 'Glitter Explosion',               subtitle: 'Sparkle.' },
  { id: 'complicated_recipe',    title: 'Overly Complicated Recipe',       subtitle: 'Burnt.' },
  { id: 'hair_flip',             title: 'Dramatic Hair Flip',              subtitle: 'Slow-mo.' },
  { id: 'cat_box',               title: 'Cat In Box',                      subtitle: 'Predictable.' },
  { id: 'calm_ocean',            title: 'Calm Ocean Loop',                 subtitle: 'Serenity.' },
];
