/**
 * Safe card content configuration.
 * Add new cards here only — visual styling is derived procedurally
 * by CardStyleController based on the card id.
 */

export interface SafeCardConfig {
  id: string;
  title: string;
  subtitle: string;
  /** Emoji icon shown on the card. Falls back to '🛡️' if absent/empty. */
  icon: string;
}

export const SAFE_CARDS_CONFIG: readonly SafeCardConfig[] = [
  { id: 'strawberry_dancing',    icon: '🍓🕺', title: 'Strawberry Dancing',               subtitle: 'This strawberry has better moves than you.' },
  { id: 'butterfly_flying',      icon: '🦋',   title: 'Butterfly Flying',                 subtitle: 'Majestic. Inspirational. Useless.' },
  { id: 'taxi_7788',             icon: '🚕',   title: 'Taxi 7788 Ad',                     subtitle: 'Call now. We probably answer.' },
  { id: 'fruit_circle',          icon: '🍉🪩', title: 'Fruit Circle Dance',               subtitle: "Nature's nightclub." },
  { id: 'cat_reviews_water',     icon: '🐱💧', title: 'Cat Reviews Water',                subtitle: 'Still wet. 10/10.' },
  { id: 'grandma_filters',       icon: '👵✨', title: 'Grandma Discovers Filters',        subtitle: 'She is now 19 again.' },
  { id: 'dog_sunglasses',        icon: '🐶🕶️', title: 'Dog With Sunglasses',              subtitle: 'Too cool to fetch.' },
  { id: 'frog_dj',               icon: '🐸🎧', title: 'Frog DJ Set',                      subtitle: 'Ribbit remix.' },
  { id: 'man_explains',          icon: '🤷📣', title: 'Man Explains Nothing',             subtitle: 'Wait for it…' },
  { id: 'slime_cut',             icon: '🫧🔪', title: 'Satisfying Slime Cut',             subtitle: 'Oddly addictive.' },
  { id: 'weather_forecast',      icon: '🌪️🌤️', title: 'Dramatic Weather Forecast',        subtitle: "It's windy." },
  { id: 'motivational_potato',   icon: '🥔💪', title: 'Motivational Potato',              subtitle: 'You are starch-strong.' },
  { id: 'invisible_prank',       icon: '🫥😈', title: 'Invisible Prank',                  subtitle: 'Did you see it?' },
  { id: 'support_duck',          icon: '🦆❤️', title: 'Emotional Support Duck',           subtitle: 'Quack therapy.' },
  { id: 'perfect_pancake',       icon: '🥞⭕', title: 'Suspiciously Perfect Pancake',     subtitle: 'Too round.' },
  { id: 'diy_glue',              icon: '🧴🛠️', title: 'DIY With Glue',                    subtitle: 'This will not hold.' },
  { id: 'ai_celebrity',          icon: '🤖🌟', title: 'AI Generated Celebrity',           subtitle: 'Almost believable.' },
  { id: 'overacting_actor',      icon: '🎭😱', title: 'Overacting Actor',                 subtitle: 'Oscar-worthy in his mind.' },
  { id: 'man_runs',              icon: '🏃💨', title: 'Man Runs From Nothing',            subtitle: 'Cardio panic.' },
  { id: 'cat_yoga',              icon: '🐈🧘', title: 'Cat Interrupts Yoga',              subtitle: 'Balance lost.' },
  { id: 'tech_bro',              icon: '💻📈', title: 'Tech Bro Advice',                  subtitle: 'Just pivot.' },
  { id: 'barista',               icon: '☕⚡', title: 'Hyperactive Barista',              subtitle: 'Extra foam.' },
  { id: 'fruit_sunglasses',      icon: '🍍🕶️', title: 'Fruit With Sunglasses',            subtitle: 'Vitamin drip.' },
  { id: 'fake_lifehack',         icon: '🧪❌', title: 'Fake Lifehack',                    subtitle: "Doesn't work." },
  { id: 'slow_motion_jump',      icon: '🦘🐢', title: 'Slow Motion Jump',                 subtitle: 'Gravity wins.' },
  { id: 'makeup_reveal',         icon: '💄🎬', title: 'Dramatic Makeup Reveal',           subtitle: 'Same person.' },
  { id: 'sad_hamster',           icon: '🐹😢', title: 'Sad Hamster',                      subtitle: 'Existential.' },
  { id: 'dancing_broccoli',      icon: '🥦🕺', title: 'Dancing Broccoli',                 subtitle: 'Green energy.' },
  { id: 'fish_music',            icon: '🐟🎵', title: 'Fish Reacts To Music',             subtitle: 'Vibing.' },
  { id: 'crypto_guy',            icon: '🪙💸', title: 'Guy Explains Crypto',              subtitle: 'Nobody understands.' },
  { id: 'edited_sunset',         icon: '🌅🎛️', title: 'Overedited Sunset',                subtitle: 'Too orange.' },
  { id: 'clumsy_ninja',          icon: '🥷😵', title: 'Clumsy Ninja',                     subtitle: 'Almost.' },
  { id: 'grocery_list',          icon: '🛒📜', title: 'Dramatic Reading Of Grocery List', subtitle: 'Milk!' },
  { id: 'cat_knocks',            icon: '🐈🥛', title: 'Cat Knocks Glass',                 subtitle: 'Classic.' },
  { id: 'fake_interview',        icon: '🎤🎭', title: 'Fake Street Interview',            subtitle: 'Scripted.' },
  { id: 'whisper_challenge',     icon: '🤫😵', title: 'Whisper Challenge',                subtitle: 'What?' },
  { id: 'microwave_cooking',     icon: '🍲📡', title: 'Microwave Cooking',                subtitle: 'Risky.' },
  { id: 'influencer_apology',    icon: '📝😬', title: 'Influencer Apology',               subtitle: 'Notes app.' },
  { id: 'dog_hat',               icon: '🐶🎩', title: 'Dog In Tiny Hat',                  subtitle: 'Fashion icon.' },
  { id: 'slow_clap',             icon: '👏🐌', title: 'Slow Clap Compilation',            subtitle: 'Unnecessary.' },
  { id: 'intense_workout',       icon: '🏋️🔥', title: 'Overly Intense Workout',           subtitle: 'For what?' },
  { id: 'frog_mic',              icon: '🐸🎙️', title: 'Frog With Microphone',             subtitle: 'Podcast.' },
  { id: 'cat_judges',            icon: '🐱👀', title: 'Cat Judges You',                   subtitle: 'Disappointed.' },
  { id: 'fake_magic',            icon: '🎩🪄', title: 'Fake Magic Trick',                 subtitle: 'Camera cut.' },
  { id: 'emotional_bread',       icon: '🍞🥺', title: 'Emotional Bread',                  subtitle: 'Crumb feelings.' },
  { id: 'man_dances',            icon: '🕺🪩', title: 'Man Dances Alone',                 subtitle: 'Confidence.' },
  { id: 'gym_quote',             icon: '🏋️📣', title: 'Motivational Gym Quote',           subtitle: 'No pain.' },
  { id: 'baby_laugh',            icon: '👶😂', title: 'Baby Laugh Loop',                  subtitle: 'Infinite.' },
  { id: 'robot_fail',            icon: '🤖💥', title: 'Robot Fails Task',                 subtitle: 'Try again.' },
  { id: 'coffee_pour',           icon: '☕🫗', title: 'Smooth Coffee Pour',               subtitle: 'Aesthetic.' },
  { id: 'plot_twist',            icon: '🌀📖', title: 'Unexpected Plot Twist',            subtitle: 'Still safe.' },
  { id: 'fake_news',             icon: '📰🤥', title: 'Fake Celebrity News',              subtitle: 'Not true.' },
  { id: 'door_open',             icon: '🚪😮', title: 'Dramatic Door Open',               subtitle: 'Nothing.' },
  { id: 'cat_attitude',          icon: '🐈👑', title: 'Cat With Attitude',                subtitle: 'Royal.' },
  { id: 'bubble_wrap',           icon: '🫧📦', title: 'Bubble Wrap ASMR',                 subtitle: 'Pop.' },
  { id: 'tourist',               icon: '🧳📸', title: 'Overenthusiastic Tourist',         subtitle: 'WOW.' },
  { id: 'skateboard_fail',       icon: '🛹💥', title: 'Skateboard Fail',                  subtitle: 'Almost.' },
  { id: 'makeup_wrong',          icon: '💄😵', title: 'Makeup Tutorial Gone Wrong',       subtitle: 'Oops.' },
  { id: 'parrot',                icon: '🦜🗯️', title: 'Pet Parrot Commentary',            subtitle: 'Rude.' },
  { id: 'banana_phone',          icon: '🍌📞', title: 'Banana Phone',                     subtitle: 'Ring ring.' },
  { id: 'confused_math',         icon: '🧮😵', title: 'Confused Math Teacher',            subtitle: 'Why?' },
  { id: 'office_dance',          icon: '🕺💼', title: 'Dancing Office Worker',            subtitle: 'Productivity.' },
  { id: 'suspicious_sandwich',   icon: '🥪🕵️', title: 'Suspicious Sandwich',              subtitle: 'Risky bite.' },
  { id: 'rain_scene',            icon: '🌧️🎬', title: 'Dramatic Rain Scene',              subtitle: 'So deep.' },
  { id: 'horror_cat',            icon: '😱🐈', title: 'Fake Horror Build-up',             subtitle: 'Just a cat.' },
  { id: 'puppy_nap',             icon: '🐶💤', title: 'Cute Puppy Nap',                   subtitle: 'Peace.' },
  { id: 'glitch_selfie',         icon: '📱🫨', title: 'Glitch Filter Selfie',             subtitle: 'Distorted.' },
  { id: 'dramatic_sip',          icon: '🫖😏', title: 'Dramatic Sip',                     subtitle: 'Tea spilled.' },
  { id: 'life_coach',            icon: '📣🧘', title: 'Life Coach Yells',                 subtitle: 'Manifest!' },
  { id: 'motivational_rock',     icon: '🪨💡', title: 'Motivational Rock',                subtitle: 'Solid advice.' },
  { id: 'cat_cucumber',          icon: '🥒😾', title: 'Cat Vs Cucumber',                  subtitle: 'Classic chaos.' },
  { id: 'desk_setup',            icon: '🖥️🧼', title: 'Minimalist Desk Setup',            subtitle: 'Expensive.' },
  { id: 'eyebrow_raise',         icon: '🤨✨', title: 'Dramatic Eyebrow Raise',           subtitle: 'Scandal.' },
  { id: 'viral_challenge',       icon: '📱🏆', title: 'Fake Viral Challenge',             subtitle: 'Nobody asked.' },
  { id: 'slow_blink',            icon: '😌👁️', title: 'Slow Blink Compilation',           subtitle: 'Trust.' },
  { id: 'shiny_sneakers',        icon: '👟✨', title: 'Shiny Sneakers',                   subtitle: 'Too clean.' },
  { id: 'ice_drop',              icon: '🧊💧', title: 'Dramatic Ice Drop',                subtitle: 'Splash.' },
  { id: 'turtle_race',           icon: '🐢🏁', title: 'Pet Turtle Race',                  subtitle: 'Slow but steady.' },
  { id: 'deep_quote',            icon: '🧠💬', title: 'Overly Deep Quote',                subtitle: 'Meaningless.' },
  { id: 'coffee_fail',           icon: '☕❌', title: 'Coffee Art Fail',                  subtitle: 'Blob.' },
  { id: 'fan_whisper',           icon: '🪭🤫', title: 'Whispering Into Fan',              subtitle: 'Vibrato.' },
  { id: 'edited_sky',            icon: '🌌🎛️', title: 'Overedited Sky',                   subtitle: 'Unreal.' },
  { id: 'banana_slip',           icon: '🍌🧎', title: 'Banana Slip',                      subtitle: 'Cartoon physics.' },
  { id: 'serious_cat',           icon: '🐱💼', title: 'Serious Cat',                      subtitle: 'CEO.' },
  { id: 'motivational_alarm',    icon: '⏰💪', title: 'Motivational Alarm',               subtitle: 'Wake up.' },
  { id: 'dog_mirror',            icon: '🐶🪞', title: 'Dog Confused By Mirror',           subtitle: 'Identity crisis.' },
  { id: 'frog_meditation',       icon: '🐸🧘', title: 'Frog Meditation',                  subtitle: 'Zen.' },
  { id: 'man_plant',             icon: '🪴🗣️', title: 'Man Talks To Plant',               subtitle: 'Therapy.' },
  { id: 'fitness_hack',          icon: '🏋️❌', title: 'Fake Fitness Hack',                subtitle: 'Nope.' },
  { id: 'dramatic_typing',       icon: '⌨️😤', title: 'Dramatic Typing',                  subtitle: 'Email.' },
  { id: 'squirrel_snack',        icon: '🐿️🥜', title: 'Squirrel With Snack',              subtitle: 'Focused.' },
  { id: 'overhyped_trailer',     icon: '🎞️📣', title: 'Overhyped Trailer',                subtitle: 'For nothing.' },
  { id: 'traffic_cone',          icon: '🚧🕺', title: 'Dancing Traffic Cone',             subtitle: 'Why?' },
  { id: 'fake_psychic',          icon: '🔮🤥', title: 'Fake Psychic Reading',             subtitle: 'Vague.' },
  { id: 'sad_violin',            icon: '🎻😢', title: 'Sad Violin Moment',                subtitle: 'Tiny tragedy.' },
  { id: 'glitter_explosion',     icon: '✨💥', title: 'Glitter Explosion',                subtitle: 'Sparkle.' },
  { id: 'complicated_recipe',    icon: '🧑‍🍳📚', title: 'Overly Complicated Recipe',        subtitle: 'Burnt.' },
  { id: 'hair_flip',             icon: '💇‍♀️💨', title: 'Dramatic Hair Flip',               subtitle: 'Slow-mo.' },
  { id: 'cat_box',               icon: '🐱📦', title: 'Cat In Box',                       subtitle: 'Predictable.' },
  { id: 'calm_ocean',            icon: '🌊😌', title: 'Calm Ocean Loop',                  subtitle: 'Serenity.' },
];
